### ISSUE TITLE
Download Textures (feature)

### ISSUE THREAD

**Issue by Scout24HD** [2231puppy/mcreator-httpapi#1]
i have a nice idea for the Plugin:
Add a Procedure this Download Textures form a website with a URL
and this put then the texture automatic in the Texture folder

**Comment by miameows** [comment]
Good idea! It might not be possible though, let me take a look.

**Comment by Scout24HD** [comment]
> 
> 
> Good idea! It might not be possible though, let me take a look.

i have see things in forge (its is possible) but very difficulty

**Comment by miameows** [comment]
I don't think this is possible as an MCreator plugin(at least with my skill level), sorry.
