### ISSUE TITLE
Idea Get source code

### ISSUE THREAD

**Issue by EyuphanMandiraci** [2231puppy/mcreator-httpapi#2]
please add " get source code of "link" " procedure

**Comment by miameows** [comment]
Do you mean getting the raw HTML? I would need a way to parse it. I could try doing JSON, but if the server gives a non-JSON response, then it would not work. I can't really parse pure HTML. I'll look into JSON.

**Comment by EyuphanMandiraci** [comment]
i mean get source code like plain text without parse. But If you do it json parse it will do.

**Comment by miameows** [comment]
I think I will try to implement this now, wish me luck 😃 

It might take a few days/weeks, but I have an idea on how to do it now. Documentation for plugin creation is sparse.

**Comment by EyuphanMandiraci** [comment]
Good luck, https://github.com/Goldorion/File-Manager-MCreator This plugin have JSON parsing

**Comment by miameows** [comment]
@EyuphanMandiraci I finished - Right now, it returns the raw HTML. I just want a little outside input - Do you think that's good? If so, I will publish it.
P.S. Thanks for the input! I don't like it when I write to devs and they don't reply, so I strive to do the opposite and make my work better.

**Comment by EyuphanMandiraci** [comment]
i think, that's good

**Comment by miameows** [comment]
Thanks! Closing this issue as I'm about to publish the new plugin.
